# Generated by Django 5.0.7 on 2024-08-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='task_description',
        ),
        migrations.AddField(
            model_name='task',
            name='task_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
