# Generated by Django 5.0.7 on 2024-08-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_task_url_user_avatar_alter_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
