# Generated by Django 5.0.7 on 2024-08-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_user_password_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
