# Generated by Django 5.0.7 on 2024-08-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_globaltask_usertaskstatus_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltask',
            name='task_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='usertaskstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user'),
        ),
    ]
